config/routes.rb
Rails.application.routes.draw do
  resources :vopportunity_enrolments
  resources :vheros
  resources :vorganizations do
    resources :vopportunities
  end
  resources :vopportunities, only: :show do
    resources :vopportunity_enrolments, only: :create
  end
  resources :vopportunities
  resources :vorganizations
    
  get 'home/index'
  root 'home#index'    
    
	# -----New Vhero/Vorganization Functionality-----
	
    # We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'vheros#new'
    root to: 'vorganizations#new'
	# sign up page with form:
	#get 'vheros/new' => 'vheros#new', :as => :new_vhero
    #get 'vorganizations/new' => 'vorganizations#new', :as => :new_vorganization
    # create (post) action for when sign up form is submitted:
	post 'vheros' => 'vheros#create'
    post 'vorganizations' => 'vorganizations#create'
  	# ----- End Vhero/Vorganization Functionality-----
    
    # ---- Login/Logout Routes ----
    get '/vherologin'     => 'sessions#vheronew'
    get '/vorglogin'     => 'sessions#vorgnew'
    # create (post) action for when log in form is submitted:
    post '/vherologin'    => 'sessions#vherocreate'
    post '/vorglogin'    => 'sessions#vorgcreate'
    # delete action to log out:
    delete '/vherologout' => 'sessions#vherodestroy'  
    delete '/vorglogout' => 'sessions#vorgdestroy'
end

app/models/vopportunity_enrolment.rb
class VopportunityEnrolment < ApplicationRecord
    belongs_to :vopportunity
    belongs_to :vhero
    accepts_nested_attributes_for :vopportunity
end

app/controllers/vopportunity_enrolments_controller.rb
class VopportunityEnrolmentsController < ApplicationController
  before_action :set_vopportunity, only: [:create]

  # GET /vopportunity_enrolments
  # GET /vopportunity_enrolments.json
  def index
    @vopportunity_enrolments = VopportunityEnrolment.all
  end

  # GET /vopportunity_enrolments/1
  # GET /vopportunity_enrolments/1.json
  def show
  end

  # GET /vopportunity_enrolments/new
  def new
    @vopportunity_enrolment = VopportunityEnrolment.new
  end

  # GET /vopportunity_enrolments/1/edit
  def edit
  end

  # POST /vopportunity_enrolments
  # POST /vopportunity_enrolments.json
  def create
    #Old scaffold code
    # @vopportunity_enrolment = VopportunityEnrolment.new(vopportunity_enrolment_params)  
    #@vopportunity = Vopportunity.find(params[:vopportunity_id])
    #@vopportunity_enrolment = VopportunityEnrolment.new(vhero_id: current_user.id, vopportunity_id: @vopportunity.id)
    
    @vopportunity_enrolment = @vopportunity.vopportunity_enrolments.build
    @vopportunity_enrolment.vhero_id = current_user.id
      
    respond_to do |format|
        if @vopportunity_enrolment.update(vopportunity_enrolment_params)
          format.html { redirect_to @vopportunity, notice: 'Congratulations! You have successfully enrolled!' }
            format.json { render :show, status: :created, location: @vopportunity }
          else
            format.html { render :new }
            format.json { render json: @vopportunity_enrolment.errors, status: :unprocessable_entity }
        end
    end

    #respond_to do |format|
     # if @vopportunity_enrolment.save
      #  format.html { redirect_to @vopportunity_enrolment, notice: 'Vopportunity enrolment was successfully created.' }
       # format.json { render :show, status: :created, location: @vopportunity_enrolment }
      #else
        #format.html { render :new }
        #format.json { render json: @vopportunity_enrolment.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /vopportunity_enrolments/1
  # PATCH/PUT /vopportunity_enrolments/1.json
  def update
    respond_to do |format|
      if @vopportunity_enrolment.save(vopportunity_enrolment_params)
        format.html { redirect_to @vopportunity_enrolment, notice: 'Enrolled! Congratulations!' }
        format.json { render :show, status: :ok, location: @vopportunity_enrolment }
      else
        format.html { render :edit }
        format.json { render json: @vopportunity_enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vopportunity_enrolments/1
  # DELETE /vopportunity_enrolments/1.json
  def destroy
    @vopportunity_enrolment = VopportunityEnrolment.find_by(vhero_id: params[:vhero_id], vopportunity_id: params[:id])
    @vopportunity_enrolment.destroy
    respond_to do |format|
      format.html { redirect_to vopportunity_path, notice: 'Enrollment was successfully cancelled.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vopportunity_enrolment
      @vopportunity_enrolment = VopportunityEnrolment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vopportunity_enrolment_params
      params.permit(:vopportunity_enrolment).permit(:vhero_id, :vopportunity_id)
    end
    
    def set_vopportunity
        @vopportunity = Vopportunity.find(params[:vopportunity_id])
    end
end

app/helpers/vopportunity_enrolments_helper.rb
module VopportunityEnrolmentsHelper
end

app/views/vopportunity_enrolments/_form.html.erb
<%= form_with(model: vopportunity_enrolment, local: true) do |form| %>
  <% if vopportunity_enrolment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vopportunity_enrolment.errors.count, "error") %> prohibited this vopportunity_enrolment from being saved:</h2>

      <ul>
      <% vopportunity_enrolment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vhero_id %>
    <%= form.number_field :vhero_id %>
  </div>

  <div class="field">
    <%= form.label :vopportunity_id %>
    <%= form.number_field :vopportunity_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vopportunity_enrolments/edit.html.erb
<h1>Editing Vopportunity Enrolment</h1>

<%= render 'form', vopportunity_enrolment: @vopportunity_enrolment %>

<%= link_to 'Show', @vopportunity_enrolment %> |
<%= link_to 'Back', vopportunity_enrolments_path %>

app/views/vopportunity_enrolments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vopportunity Enrolments</h1>

<table>
  <thead>
    <tr>
      <th>Vhero</th>
      <th>Vopportunity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vopportunity_enrolments.each do |vopportunity_enrolment| %>
      <tr>
        <td><%= vopportunity_enrolment.vhero_id %></td>
        <td><%= vopportunity_enrolment.vopportunity_id %></td>
        <td><%= link_to 'Show', vopportunity_enrolment %></td>
        <td><%= link_to 'Edit', edit_vopportunity_enrolment_path(vopportunity_enrolment) %></td>
        <td><%= link_to 'Destroy', vopportunity_enrolment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vopportunity Enrolment', new_vopportunity_enrolment_path %>

app/views/vopportunity_enrolments/new.html.erb
<h1>New Vopportunity Enrolment</h1>

<%= render 'form', vopportunity_enrolment: @vopportunity_enrolment %>

<%= link_to 'Back', vopportunity_enrolments_path %>

app/views/vopportunity_enrolments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vhero:</strong>
  <%= @vopportunity_enrolment.vhero_id %>
</p>

<p>
  <strong>Vopportunity:</strong>
  <%= @vopportunity_enrolment.vopportunity_id %>
</p>

<%= link_to 'Edit', edit_vopportunity_enrolment_path(@vopportunity_enrolment) %> |
<%= link_to 'Back', vopportunity_enrolments_path %>