config/routes.rb
Rails.application.routes.draw do
  resources :vopportunity_enrolments
  resources :vheros
  resources :vorganizations do
    resources :vopportunities
  end
  resources :vopportunities, only: :show do
    resources :vopportunity_enrolments, only: :create
  end
  resources :vopportunities
  resources :vorganizations
    
  get 'home/index'
  root 'home#index'    
    
	# -----New Vhero/Vorganization Functionality-----
	
    # We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'vheros#new'
    root to: 'vorganizations#new'
	# sign up page with form:
	#get 'vheros/new' => 'vheros#new', :as => :new_vhero
    #get 'vorganizations/new' => 'vorganizations#new', :as => :new_vorganization
    # create (post) action for when sign up form is submitted:
	post 'vheros' => 'vheros#create'
    post 'vorganizations' => 'vorganizations#create'
  	# ----- End Vhero/Vorganization Functionality-----
    
    # ---- Login/Logout Routes ----
    get '/vherologin'     => 'sessions#vheronew'
    get '/vorglogin'     => 'sessions#vorgnew'
    # create (post) action for when log in form is submitted:
    post '/vherologin'    => 'sessions#vherocreate'
    post '/vorglogin'    => 'sessions#vorgcreate'
    # delete action to log out:
    delete '/vherologout' => 'sessions#vherodestroy'  
    delete '/vorglogout' => 'sessions#vorgdestroy'
end

app/models/vorganization.rb
class Vorganization < ApplicationRecord
    validates :vorgname, presence: true,
                       length: { minimum: 5 }
    validates :email, presence: true, uniqueness: true
    has_many :vopportunities, dependent: :destroy
    has_secure_password
end

app/controllers/vorganizations_controller.rb
class VorganizationsController < ApplicationController
  before_action :set_vorganization, only: [:show, :edit, :update, :destroy]
  before_action :vorgauthorize, only: [:edit, :update, :destroy]
  layout "orgapplication"
    
  # GET /vorganizations
  # GET /vorganizations.json
  def index
    @vorganizations = Vorganization.all
  end

  # GET /vorganizations/1
  # GET /vorganizations/1.json
  def show
  end

  # GET /vorganizations/new
  def new
    @vorganization = Vorganization.new
  end

  # GET /vorganizations/1/edit
  def edit
  end

  # POST /vorganizations
  # POST /vorganizations.json
  def create
    @vorganization = Vorganization.new(vorganization_params)
    @vorganization.email.downcase!
    
    respond_to do |format|
      if @vorganization.save
        format.html { redirect_to vorglogin_path, notice: 'Your account was created successfully. Please log in.' }
        format.json { render :show, status: :created, location: @vorganization }
      else
        format.html { render :new }
        flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      end
    end
  end

  # PATCH/PUT /vorganizations/1
  # PATCH/PUT /vorganizations/1.json
  def update
    respond_to do |format|
      if @vorganization.update(vorganization_params)
        format.html { redirect_to @vorganization, notice: 'Vorganization was successfully updated.' }
        format.json { render :show, status: :ok, location: @vorganization }
      else
        format.html { render :edit }
        format.json { render json: @vorganization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vorganizations/1
  # DELETE /vorganizations/1.json
  def destroy
    @vorganization.destroy
    respond_to do |format|
      format.html { redirect_to vorganizations_url, notice: 'Vorganization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vorganization
      @vorganization = Vorganization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vorganization_params
      params.require(:vorganization).permit(:vorgname, :website, :vorglogo, :shortdescr, :vorgtype, :city, :province, :country, :handles, :email, :password, :password_confirmation)
    end
end

app/helpers/vorganizations_helper.rb
module VorganizationsHelper
end

app/views/vorganizations/_form.html.erb
<%= form_with(model: vorganization, local: true) do |form| %>
  <% if vorganization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vorganization.errors.count, "error") %> prohibited this vorganization from being saved:</h2>

      <ul>
      <% vorganization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vorgname %>
    <%= form.text_field :vorgname %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="field">
    <%= form.label :vorglogo %>
    <%= form.text_field :vorglogo %>
  </div>

  <div class="field">
    <%= form.label :shortdescr %>
    <%= form.text_area :shortdescr %>
  </div>

  <div class="field">
    <%= form.label :vorgtype %>
    <%= form.text_field :vorgtype %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :province %>
    <%= form.text_field :province %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :handles %>
    <%= form.text_field :handles %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vorganizations/_newvopportunity.html.erb
<p><h1>Add an opportunity:</h1></p>

<%= form_with(model: [ @vorganization, @vorganization.vopportunities.build ], local: true) do |form| %>

  <div class="field">
    <%= form.label :voppname %>
    <%= form.text_field :voppname %>
  </div>

  <div class="field">
    <%= form.label :vopplogo %>
    <%= form.text_field :vopplogo %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :shortdescr %>
    <%= form.text_field :shortdescr %>
  </div>

  <div class="field">
    <%= form.label :vorganization_id %>
    <%= form.number_field :vorganization_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vorganizations/_showvopportunity.html.erb
<p>
    <h2>Current Opportunities</h2>
        <table>
          <thead>
            <tr>
              <th>Voppname</th>
              <th>Vopplogo</th>
              <th>Title</th>
              <th>Shortdescr</th>
              <th>Vorganization</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @vorganization.vopportunity.each do |vopportunity| %>
              <tr>
                <td><%= vopportunity.voppname %></td>
                <td><%= vopportunity.vopplogo %></td>
                <td><%= vopportunity.title %></td>
                <td><%= vopportunity.shortdescr %></td>
                <td><%= vopportunity.vorganization_id %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
</p>

app/views/vorganizations/edit.html.erb
<h1>Editing Vorganization</h1>

<%= render 'form', vorganization: @vorganization %>

<%= link_to 'Show', @vorganization %> |
<%= link_to 'Back', vorganizations_path %>

app/views/vorganizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vorganizations</h1>

<table>
  <thead>
    <tr>
      <th>Vorgname</th>
      <th>Website</th>
      <th>Vorglogo</th>
      <th>Shortdescr</th>
      <th>Vorgtype</th>
      <th>City</th>
      <th>Province</th>
      <th>Country</th>
      <th>Handles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vorganizations.each do |vorganization| %>
      <tr>
        <td><%= vorganization.vorgname %></td>
        <td><%= vorganization.website %></td>
        <td><%= vorganization.vorglogo %></td>
        <td><%= vorganization.shortdescr %></td>
        <td><%= vorganization.vorgtype %></td>
        <td><%= vorganization.city %></td>
        <td><%= vorganization.province %></td>
        <td><%= vorganization.country %></td>
        <td><%= vorganization.handles %></td>
        <td><%= link_to 'Show', vorganization %></td>
        <td><%= link_to 'Edit', edit_vorganization_path(vorganization) %></td>
        <td><%= link_to 'Destroy', vorganization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_vorganization_path %>

<br>

<%= link_to 'Home', home_index_path %>

app/views/vorganizations/new.html.erb
<main class="page-content">  
        <!-- Breadcrumbs & Page title -->
        <section class="text-center section-34 section-sm-60 section-md-top-100 section-md-bottom-105 bg-image bg-breadcrumbs-01">
          <div class="shell shell-fluid">
            <div class="range range-condensed">
              <div class="cell-xs-12 cell-xl-preffix-1 cell-xl-11">
                <p class="h3 text-white">Become a Volunthero Organization</p>
              </div>
            </div>
          </div>
        </section>
        <section class="bg-white text-center section-50 section-sm-bottom-100">
          <div class="shell">
            <div class="range range-xs-center offset-top-15">
              <div class="cell-sm-10 cell-md-8">
                <div class="inset-lg-left-50 inset-lg-right-50">
                  <!-- RD Mailform-->
                    <%= form_with(model: @vorganization, local: true) do |form| %>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :vorgname, autofocus: true, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :vorgname, "Name" %></label>
                        </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :vorgaddress, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :vorgname, "Address" %></label>
                        </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :website, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :website, "Website" %></label>
                        </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.select :vorgtype, ['Charity/Non-Profit', 'Private', 'Other']%>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :vorgtype, "Org. Type" %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :vorglogo, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :vorglogo, "Logo" %></label>
                      </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :city, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :city, "City" %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :province, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :province, "State/Province" %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :country, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :country, "Country" %></label>
                      </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :email, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :email, "Email" %></label>
                      </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.password_field :password, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :password, "Password" %></label>
                      </div>
                      <div class="form-group">
                        <%= form.password_field :password_confirmation, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :password_confirmation, "Password Confirmation" %></label>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group offset-top-15">
                        <%= form.text_area :aboutus, class: "form-control" %> 
                        <label for="message" class="form-label form-label-outside"> <%= form.label :aboutus, "About Us" %></label>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <div class="form-inline-flex">
                      <div class="form-group offset-top-15">
                        <%= form.text_area :shortdescr, class: "form-control" %> 
                        <label for="message" class="form-label form-label-outside"> <%= form.label :shortdescr, "Our Mission" %></label>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :handles, autofocus: true, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :handles, "Social Media Handles" %></label>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="offset-top-15">
                      <div class="form-inline-flex">
                        <div class="form-group">
                          <%= form.submit "Sign Up", class: "btn btn-burnt-sienna btn-fullwidth btn-shadow" %>
                          <!--<button type="submit" class="btn btn-burnt-sienna btn-fullwidth">Send message</button>-->
                        </div>
                        <% end %>
                      </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </section>
</main>
    <%= javascript_include_tag "core.min" %>
    <%= javascript_include_tag "script" %>
<%= link_to 'Back', vorganizations_path %>

app/views/vorganizations/show.html.erb
<!--Page > Vorganization profile page-->
        <section class="section-top-50 section-sm-top-100">
          <div class="shell">
            <div class="range range-xs-center">
              <div class="cell-sm-7 cell-md-6">
                <div class="img-thumbnail-custom"><img src="<%= image_path (@vorganization.vorglogo) unless @vorganization.vorglogo.blank? %>" alt="Profile Picture" width="569" height="656" class="img-responsive"/>
                  <!--<div class="caption">
                    <div class="group-lg">
                      <ul class="list-inline text-middle">
                        <li><a href="#" class="link-white icon icon-sm icon-circle fa-instagram"></a></li>
                        <li><a href="#" class="link-white icon icon-xs icon-circle fa-facebook"></a></li>
                        <li><a href="#" class="link-white icon icon-xs icon-circle fa-twitter"></a></li>
                        <li><a href="#" class="link-white icon icon-xs icon-circle fa-google-plus"></a></li>
                      </ul>
                    </div>
                  </div>-->
                </div>
              </div>
              <div class="cell-sm-7 cell-md-6 text-sm-left offset-sm-top-30 offset-md-top-0">
                <div class="inset-lg-left-70">
                  <div class="reveal-xs-flex range-xs-justify range-xs-middle">
                    <h4 class="font-default"><%= @vorganization.vorgname %></h4>
                    <div class="team-member-position offset-top-0"><span class="big text-italic text-middle"><%= @vorganization.vorgtype %></span></div>
                  </div>
                  <div class="offset-top-10">
                    <ul class="list-inline list-inline-sm">
                      <li>
                        <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                          <div class="unit-left"><span class="icon icon-xs text-primary mdi mdi-email-outline text-middle"></span></div>
                          <div class="unit-body"><%= link_to @vorganization.email, class: "link-default" %></div>
                        </div>
                      </li>
                    </ul>
                  </div>
                  <p class="offset-top-20"><%= @vorganization.shortdescr %></p>
                  <p class="offset-top-20"><%= link_to 'Edit', edit_vorganization_path(@vorganization), class: "btn btn-burnt-sienna btn-fullwidth btn-shadow" %></p>
                </div>
              </div>
            </div>
          </div>
          </section>
          <br><br>
          <section class="text-center text-sm-left section-50 section-sm-top-80 section-sm-bottom-100 bg-ecru-white">
          <div class="shell">
            <p align="center"><%= link_to 'Post New Opportunity', new_vorganization_vopportunity_path(@vorganization), class: "btn btn-burnt-sienna" %></p>
            <h4 class="font-default text-center"><%=@vorganization.vorgname %>'s Posted Opportunities</h4>
            <% x = 2 %>
            <% @vorganization.vopportunities.each do |vorgposting| 
            if vorgposting.present?
            if x.even? %>
            <div class="range">
              <div class="cell-sm-6">
                <div class="job-offer bg-white">
                  <%= link_to vorgposting, class: "h5" do %>
                  <%= vorgposting.voppname %>
                  <% end %>
                  <ul class="list-inline offset-top-10">
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-map-marker"></span><span class="text-middle"><%= vorgposting.created_at.strftime ("%B %-d, %Y") %></span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-clock"></span><span class="text-middle"><%= vorgposting.deadlinedate.strftime ("%B %-d, %Y") %></span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-calendar"></span><span class="text-middle"><%= vorgposting.voppdate.strftime ("%B %-d, %Y") %></span></li>
                  </ul>
                </div>
              </div>
            <% x = x + 1
            else %>
            <div class="cell-sm-6 offset-top-30 offset-sm-top-0">
                <div class="job-offer bg-white">
                  <%= link_to vorgposting, class: "h5" do %>
                  <%= vorgposting.voppname %>
                  <% end %>
                  <ul class="list-inline offset-top-10">
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-map-marker"></span><span class="text-middle"><%= vorgposting.created_at.strftime ("%B %-d, %Y") %></span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-clock"></span><span class="text-middle"><%= vorgposting.deadlinedate.strftime ("%B %-d, %Y") %></span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-calendar"></span><span class="text-middle"><%= vorgposting.voppdate.strftime ("%B %-d, %Y") %></span></li>
                  </ul>
                </div>
              </div>
            </div>
            <% x = x + 1
               end
               end
             end %>
            </div>
          </div>
        </section>
      </main>
    </div>
    <%= javascript_include_tag "core.min" %>
    <%= javascript_include_tag "script" %>
<%= link_to 'Back', vorganizations_path %>