config/routes.rb
Rails.application.routes.draw do
  resources :vopportunity_enrolments
  resources :vheros
  resources :vorganizations do
    resources :vopportunities
  end
  resources :vopportunities, only: :show do
    resources :vopportunity_enrolments, only: :create
  end
  resources :vopportunities
  resources :vorganizations
    
  get 'home/index'
  root 'home#index'    
    
	# -----New Vhero/Vorganization Functionality-----
	
    # We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'vheros#new'
    root to: 'vorganizations#new'
	# sign up page with form:
	#get 'vheros/new' => 'vheros#new', :as => :new_vhero
    #get 'vorganizations/new' => 'vorganizations#new', :as => :new_vorganization
    # create (post) action for when sign up form is submitted:
	post 'vheros' => 'vheros#create'
    post 'vorganizations' => 'vorganizations#create'
  	# ----- End Vhero/Vorganization Functionality-----
    
    # ---- Login/Logout Routes ----
    get '/vherologin'     => 'sessions#vheronew'
    get '/vorglogin'     => 'sessions#vorgnew'
    # create (post) action for when log in form is submitted:
    post '/vherologin'    => 'sessions#vherocreate'
    post '/vorglogin'    => 'sessions#vorgcreate'
    # delete action to log out:
    delete '/vherologout' => 'sessions#vherodestroy'  
    delete '/vorglogout' => 'sessions#vorgdestroy'
end

app/models/vhero.rb
class Vhero < ApplicationRecord
    has_many :vopportunity_enrolments, :class_name => 'VopportunityEnrolment', foreign_key: "vhero_id"
    has_many :vopportunities, through: :vopportunity_enrolments, foreign_key: "vopportunity_id"
    has_secure_password
    # Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
    has_one_attached :image
	validates :email, presence: true, uniqueness: true
end

app/controllers/vheros_controller.rb
class VherosController < ApplicationController
  before_action :set_vhero, only: [:show, :edit, :update, :destroy]
  before_action :vheroauthorize, only: [:show, :edit, :update, :destroy]

  # GET /vheros
  # GET /vheros.json
  def index
    @vheros = Vhero.all
  end

  # GET /vheros/1
  # GET /vheros/1.json
  def show
      @vhero = Vhero.find(params[:id])
      if @vhero.image.nil?
        @vhero.image = "mitchmaner.jpg"
      end
  end

  # GET /vheros/new
  def new
    @vhero = Vhero.new
  end

  # GET /vheros/1/edit
  def edit
  end

  # POST /vheros
  # POST /vheros.json
  def create
    @vhero = Vhero.new(vhero_params)
      
    @vhero.email.downcase!

    respond_to do |format|
      if @vhero.save
        @vhero.image.attach(params[:vhero][:image])
        format.html { redirect_to vherologin_path, notice: 'Your profile was created successfully. Please log in.' }
        format.json { render :show, status: :created, location: @vhero }
      else
        format.html { render :new }
        flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
        render :new
        # Removed from scaffold code  
        # format.json { render json: @vhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vheros/1
  # PATCH/PUT /vheros/1.json
  def update
    respond_to do |format|
      if @vhero.update(vhero_params)
        format.html { redirect_to @vhero, notice: 'Vhero was successfully updated.' }
        format.json { render :show, status: :ok, location: @vhero }
      else
        format.html { render :edit }
        format.json { render json: @vhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vheros/1
  # DELETE /vheros/1.json
  def destroy
    @vhero.destroy
    respond_to do |format|
      format.html { redirect_to vheros_url, notice: 'Vhero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vhero
      @vhero = Vhero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vhero_params
      params.require(:vhero).permit(:firstname, :lastname, :email, :password, :shortdescr, :jobtitle, :organization, :lastschool, :city, :province, :country, :handles, :interests)
    end
end

app/helpers/vheros_helper.rb
module VherosHelper
end

app/views/vheros/_showenrolments.html.erb
<p>
    <h2>Enrolled Opportunities</h2>
</p>
<p>
    <% @vhero.vopportunities.each do |vheroenrolment| %>
        <table frame="box">
            <tr><td>Name: <%= link_to vheroenrolment.voppname, vopportunity_path(vheroenrolment) %></td></tr>
            <tr><td>Logo: <%= vheroenrolment.vopplogo %></td></tr>
            <tr><td>Title: <%= vheroenrolment.title %></td></tr>
            <tr><td>Description: <%= vheroenrolment.shortdescr %></td></tr>
            <tr><td>OrgName: <%= vheroenrolment.vorganization.vorgname %></td></tr>
        </table>
    <% end %>
</p>
<!--<p>
    <h2>Current Opportunities</h2>
          <% #@vopportunity = Vopportunity.not_enroled %>
          <% #@vopportunity.each do |vopportunity| %>
        <table frame="box">
            <tr><td>Name: <%= link_to vopportunity.voppname, vopportunity_path(vopportunity) %></td></tr>
            <tr><td>Logo: <%= vopportunity.vopplogo %></td></tr>
            <tr><td>Title: <%= vopportunity.title %></td></tr>
            <tr><td>Description: <%= vopportunity.shortdescr %></td></tr>
            <tr><td>Organization: <%= vopportunity.vorganization.vorgname %></td></tr>
        </table>
        <br>
            <% #end %>
</p>-->

app/views/vheros/edit.html.erb
<main class="page-content">  
        <!-- Breadcrumbs & Page title-->
        <section class="text-center section-34 section-sm-60 section-md-top-100 section-md-bottom-105 bg-image bg-breadcrumbs-01">
          <div class="shell shell-fluid">
            <div class="range range-condensed">
              <div class="cell-xs-12 cell-xl-preffix-1 cell-xl-11">
                <p class="h3 text-white">Become a Volunthero</p>
              </div>
            </div>
          </div>
        </section>
        <section class="bg-white text-center section-50 section-sm-bottom-100">
          <div class="shell">
            <div class="range range-xs-center offset-top-15">
              <div class="cell-sm-10 cell-md-8">
                <div class="inset-lg-left-50 inset-lg-right-50">
                  <!-- RD Mailform-->
                    <%= form_with(model: @vhero, local: true) do |form| %>

                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :firstname %></label><br>
                        <%= form.text_field :firstname, autofocus: true, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :lastname %></label><br>
                        <%= form.text_field :lastname, class: "form-control" %>
                      </div>
                    </div>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :city %></label><br>
                        <%= form.text_field :city, autofocus: true, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :province %></label><br>
                        <%= form.text_field :province, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :country %></label><br>
                        <%= form.text_field :country, class: "form-control" %>
                      </div>
                    </div>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :email %></label><br>
                        <%= form.text_field :email, autofocus: true, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :password %></label><br>
                        <%= form.password_field :password, class: "form-control" %>
                      </div>
                    </div>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :profile_pic %></label><br>
                        <%= form.text_field :profile_pic, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :password_confirmation %></label><br>
                        <%= form.password_field :password_confirmation, class: "form-control" %>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :jobtitle %></label><br>
                        <%= form.text_field :jobtitle, autofocus: true, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :organization %></label><br>
                        <%= form.text_field :organization, class: "form-control" %>
                      </div>
                    </div>
                    <div class="form-group offset-top-15">
                      <label for="message" class="form-label form-label-outside">
                      <%= form.label :shortdescr %></label><br>
                      <%= form.text_area :shortdescr, class: "form-control" %> 
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :handles %></label><br>
                        <%= form.text_field :handles, autofocus: true, class: "form-control" %>
                      </div>
                      <div class="form-group">
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :interests %></label><br>
                        <%= form.text_field :interests, class: "form-control" %>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="offset-top-15">
                      <div class="form-inline-flex">
                        <div class="form-group">
                          <%= form.submit "Submit", class: "btn btn-burnt-sienna btn-fullwidth btn-shadow" %>
                          <!--<button type="submit" class="btn btn-burnt-sienna btn-fullwidth">Send message</button>-->
                        </div>
                        <% end %>
                      </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </section>
</main>

<%= link_to 'Back', vheros_path %>

app/views/vheros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vheros</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Password</th>
      <th>Shortdescr</th>
      <th>Jobtitle</th>
      <th>Organization</th>
      <th>Lastschool</th>
      <th>City</th>
      <th>Province</th>
      <th>Country</th>
      <th>Handles</th>
      <th>Interests</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vheros.each do |vhero| %>
      <tr>
        <td><%= vhero.firstname %></td>
        <td><%= vhero.lastname %></td>
        <td><%= vhero.email %></td>
        <td><%= vhero.password %></td>
        <td><%= vhero.shortdescr %></td>
        <td><%= vhero.jobtitle %></td>
        <td><%= vhero.organization %></td>
        <td><%= vhero.lastschool %></td>
        <td><%= vhero.city %></td>
        <td><%= vhero.province %></td>
        <td><%= vhero.country %></td>
        <td><%= vhero.handles %></td>
        <td><%= vhero.interests %></td>
        <td><%= link_to 'Show', vhero %></td>
        <td><%= link_to 'Edit', edit_vhero_path(vhero) %></td>
        <td><%= link_to 'Destroy', vhero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'New Vhero', new_vhero_path %></p>

<p><%= link_to 'Home', home_index_path %></p>

app/views/vheros/new.html.erb
<main class="page-content">  
        <!-- Breadcrumbs & Page title -->
        <section class="text-center section-34 section-sm-60 section-md-top-100 section-md-bottom-105 bg-image bg-breadcrumbs-01">
          <div class="shell shell-fluid">
            <div class="range range-condensed">
              <div class="cell-xs-12 cell-xl-preffix-1 cell-xl-11">
                <p class="h3 text-white">Become a Volunthero</p>
              </div>
            </div>
          </div>
        </section>
        <section class="bg-white text-center section-50 section-sm-bottom-100">
          <div class="shell">
            <div class="range range-xs-center offset-top-15">
              <div class="cell-sm-10 cell-md-8">
                <div class="inset-lg-left-50 inset-lg-right-50">
                  <!-- RD Mailform-->
                    <%= form_with(model: @vhero, local: true) do |form| %>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :firstname, autofocus: true, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :firstname %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :lastname, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :lastname %></label>
                      </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :city, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :city %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :province, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :province %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :country, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :country %></label>
                      </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :email, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :email %></label>
                      </div>
                      <div class="form-group">
                        <%= form.password_field :password, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :password %></label>
                      </div>
                    </div>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.file_field :image, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :image %></label>
                      </div>
                      <div class="form-group">
                        <%= form.password_field :password_confirmation, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :password_confirmation %></label>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :jobtitle, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :jobtitle %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :organization, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :organization %></label>
                      </div>
                    </div>
                    <div class="form-group offset-top-15">
                      <%= form.text_area :shortdescr, class: "form-control" %> 
                      <label for="message" class="form-label form-label-outside">
                      <%= form.label :shortdescr %></label>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="form-inline-flex">
                      <div class="form-group">
                        <%= form.text_field :handles, autofocus: true, class: "form-control" %>
                        <label for="contact-name-2" class="form-label form-label-outside"><%= form.label :handles %></label>
                      </div>
                      <div class="form-group">
                        <%= form.text_field :interests, class: "form-control" %>
                        <label for="contact-username" class="form-label form-label-outside"><%= form.label :interests %></label>
                      </div>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <div class="offset-top-15">
                      <div class="form-inline-flex">
                        <div class="form-group">
                          <%= form.submit "Sign Up", class: "btn btn-burnt-sienna btn-fullwidth btn-shadow" %>
                          <!--<button type="submit" class="btn btn-burnt-sienna btn-fullwidth">Send message</button>-->
                        </div>
                        <% end %>
                      </div>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </section>
</main>
    <%= javascript_include_tag "core.min" %>
    <%= javascript_include_tag "script" %>
<%= link_to 'Back', vheros_path %>

app/views/vheros/show.html.erb
<!--Page > Volunthero profile page-->
        <section class="section-top-50 section-sm-top-100">
          <div class="shell">
            <div class="range range-xs-center">
              <div class="cell-sm-7 cell-md-6">
                <div class="img-thumbnail-custom"><%= image_tag @vhero.image unless @vhero.image.nil?, class: "img-responsive", alt: "You NEED a Profile Picture", resize: "569x656" %>
                </div>
              </div>
              <div class="cell-sm-7 cell-md-6 text-sm-left offset-sm-top-30 offset-md-top-0">
                <div class="inset-lg-left-70">
                  <div class="reveal-xs-flex range-xs-justify range-xs-middle">
                    <h4 class="font-default"><%= @vhero.firstname %> <%= @vhero.lastname %></h4>
                    <div class="team-member-position offset-top-0"><span class="big text-italic text-middle"><%= @vhero.jobtitle %></span></div>
                  </div>
                  <div class="offset-top-10">
                    <ul class="list-inline list-inline-sm">
                      <li>
                        <div class="unit unit-horizontal unit-middle unit-spacing-xs">
                          <div class="unit-left"><span class="icon icon-xs text-primary mdi mdi-email-outline text-middle"></span></div>
                          <div class="unit-body"><%= link_to @vhero.email, class: "link-default" %></div>
                        </div>
                      </li>
                    </ul>
                  </div>
                  <p class="offset-top-20"><%= @vhero.shortdescr %></p>
                  <p class="offset-top-20"><%= link_to 'Edit', edit_vhero_path(@vhero), class: "btn btn-burnt-sienna btn-fullwidth btn-shadow" %></p>
                </div>
              </div>
            </div>
          </div>
          </section>
          <section class="text-center text-sm-left section-50 section-sm-top-80 section-sm-bottom-100 bg-ecru-white">
          <div class="shell">
            <h4 class="font-default text-center"><%=@vhero.firstname %>'s Hero Resume</h4>
            <div class="range">
            <% x = 2 %>
            <% @vhero.vopportunities.each do |vheroenrolment| 
            if vheroenrolment.present?
            if x.even? %>
            
              <div class="cell-sm-6">
                <div class="job-offer bg-white">
                  <%= link_to vheroenrolment, class: "h5" do %>
                  <%= vheroenrolment.voppname %>
                  <% end %>
                  <ul class="list-inline offset-top-10">
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-map-marker"></span><span class="text-middle">?</span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-clock"></span><span class="text-middle">?</span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-calendar"></span><span class="text-middle"><%= vheroenrolment.created_at %></span></li>
                  </ul>
                </div>
              </div>
            <% x = x + 1
            else %>
            <div class="cell-sm-6 offset-top-30 offset-sm-top-0">
                <div class="job-offer bg-white">
                  <%= link_to vheroenrolment, class: "h5" do %>
                  <%= vheroenrolment.voppname %>
                  <% end %>
                  <ul class="list-inline offset-top-10">
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-map-marker"></span><span class="text-middle">?</span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-clock"></span><span class="text-middle">?</span></li>
                    <li><span class="text-middle icon icon-xxs icon-primary mdi mdi-calendar"></span><span class="text-middle"><%= vheroenrolment.created_at %></span></li>
                  </ul>
                </div>
              </div>
            <% x = x + 1
               end
               end
             end %>
            </div>
          </div>
        </section>
      </main>
    </div>
    <%= javascript_include_tag "core.min" %>
    <%= javascript_include_tag "script" %>
<%= link_to 'Edit', edit_vhero_path(@vhero) %> |
<%= link_to 'Back', vheros_path %>